= Automatic License Plate Recognition Demo
 
A sample of a ALPR using OpenCV, Python, Tesseract and PyTesseract.

OpenCV used to detect text ROI on images and pass then to Tessseract wich can perform text recognition based on deep learning-based model.

== OCR (optical caracter regogniiton) Environment

----
workon {alpr_env}
pip install imutils
pip install scikit-image
----

== Test Run
----
python ocr_license_plate.py --input license_plates/group1 --clear-border 1
----
== Why haven’t we applied deep learning object detection to find the license plate? Wouldn’t that be easier?”
[quote]
While that is perfectly acceptable, it is a lot of work to train such an object detector on your own. We’re talking requires countless hours to annotate thousands of images in your dataset.

But we didn’t have the luxury of a dataset in the first place, so the method we’ve developed so far relies on so-called “traditional” image processing techniques.

== References

Pyimagesearch
https://www.pyimagesearch.com/2020/09/21/opencv-automatic-license-number-plate-recognition-anpr-with-python/